import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Nabvar";

const Public = Public_Sans({
 subsets: ['latin'],
  weight: ['400', '500', '700'],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${Public.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
